before_script:
  - docker-compose -f docker-compose-gitlab.yml build
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - docker-compose -f docker-compose-gitlab.yml run php composer install

after_script:
  - docker-compose -f docker-compose-gitlab.yml down

stages:
  - code_quality
  - codeception_tests

code_quality:
  stage: code_quality
  script:
    - docker-compose -f docker-compose-gitlab.yml run php bin/phpcs src/ --standard=psr2 --extensions=php

codeception_tests:
  stage: codeception_tests
  script:
    - docker-compose -f docker-compose-gitlab.yml run php bin/console doctrine:schema:create
    - docker-compose -f docker-compose-gitlab.yml run php bin/console doctrine:migrations:migrate -n
    - docker-compose -f docker-compose-gitlab.yml run php bin/console fos:user:create admin admin@admin.com admin
    - docker-compose -f docker-compose-gitlab.yml run php bin/console fos:user:promote admin ROLE_ADMIN
    - docker-compose -f docker-compose-gitlab.yml run php bin/codecept run --steps
