easy_admin:
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }
    site_name: 'Development by Pedro Resende'
    design:
        menu:
            - { label: 'Dashboard', icon: 'dashboard', route: 'dashboard', default: true }
            - label: 'Content'
              icon: 'columns'
              children:
                - { entity: 'BlogPost', icon: 'file-o', label: 'Blog Posts' }
                - { entity: 'Page', icon: 'paper-plane', label: 'Pages' }
            - { entity: 'File', icon: 'film', label: 'Media' }
            - { entity: 'User', icon: 'user', label: 'Users' }
            - { entity: 'Contact', icon: 'address-card-o', label: 'Contacts' }
            - label: 'Setup'
              icon: 'cogs'
              children:
                - { entity: 'Setting', icon: 'cog', label: 'Settings' }
                - { entity: 'Section', icon: 'puzzle-piece', label: 'Sections' }
                - { entity: 'Language', icon: 'language', label: 'Languages' }
                - { entity: 'Status', icon: 'check-circle-o', label: 'Status' }
                - { entity: 'Alias', icon: 'share-alt', label: 'Url Alias' }
        assets:
            favicon: 'bundles/cms2base/images/favicon.ico'
            css:
                - 'bundles/cms2base/css/custom.css'
                - 'bundles/cms2base/css/dropzone.css'
            js:
                - 'bundles/cms2base/js/dropzone.min.js'
                - '//cdn.tinymce.com/4/tinymce.min.js'
                - 'bundles/cms2base/js/tinymce.js'
                - 'bundles/cms2base/js/custom.js'
    entities:
        - Contact:
          class: CMS2\BaseBundle\Entity\Contact
          disabled_actions: ['new']
          list:
              title: Contacts
        - Setting:
          class: CMS2\BaseBundle\Entity\Setting
          disabled_actions: ['new', 'delete', 'search']
          list:
              title: Settings
              max_results: 1
        - BlogPost:
          class: CMS2\BaseBundle\Entity\BlogPost
          form:
              fields:
                  - title
                  - subtitle
                  - author
                  - text
                  - date
                  - tag
                  - category
                  - section
                  - language
                  - status
        - Page:
          class: CMS2\BaseBundle\Entity\Page
          form:
              fields:
                  - title
                  - text
                  - date
                  - section
                  - language
                  - status
        - CMS2\BaseBundle\Entity\Section
        - CMS2\BaseBundle\Entity\Language
        - CMS2\BaseBundle\Entity\Status
        - Alias:
          class: CMS2\BaseBundle\Entity\Alias
          list:
            fields:
              - 'id'
              - 'url'
              - 'space'
        - CMS2\BaseBundle\Entity\User
        - File:
          class: CMS2\BaseBundle\Entity\File
          disabled_actions: ['new', 'edit', 'show']
          list:
            title: Files
            fields:
                - 'id'
                - 'name'
                - { property: 'filename', type: 'image', base_path: '%files_location%' }
                - 'type'
                - 'date' 
                - 'size'
