easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

cms2_override_fos_user:
    resource: "@CMS2OverrideFOSUserBundle/Resources/config/routing.yml"
    prefix:   /

cms2_base:
    resource: "@CMS2BaseBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
