easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:     /admin

cms2_rest:
    type: rest
    resource: "@CMS2RestBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

cms2_base:
    resource: "@CMS2BaseBundle/Resources/config/routing.yml"
    prefix:   /
