alias:
    type:     rest
    prefix: alias
    resource: CMS2\RestBundle\Controller\AliasController
    name_prefix:  alias_

blogposts:
    type:     rest
    prefix: blogpost
    resource: CMS2\RestBundle\Controller\BlogPostsController
    name_prefix:  blogpost_

contacts:
    type:     rest
    prefix: contact
    resource: CMS2\RestBundle\Controller\ContactsController
    name_prefix:  contact_

files:
    type:     rest
    prefix: file
    resource: CMS2\RestBundle\Controller\FilesController
    name_prefix:  file_

languages:
    type:     rest
    prefix: language
    resource: CMS2\RestBundle\Controller\LanguagesController
    name_prefix:  language_

pages:
    type:     rest
    prefix: page
    resource: CMS2\RestBundle\Controller\PagesController
    name_prefix:  page_

sections:
    type:     rest
    prefix: section
    resource: CMS2\RestBundle\Controller\SectionsController
    name_prefix:  section_

status:
    type:     rest
    prefix: status
    resource: CMS2\RestBundle\Controller\StatusController
    name_prefix:  status_
