dashboard:
    path: admin/dashboard
    defaults: { _controller: CMS2BaseBundle:Dashboard:index }
    methods:  [GET]

newfile:
    path: admin/fileUpload
    defaults: { _controller: CMS2BaseBundle:File:newFile }
    methods:  [POST]

list_files:
    path: admin/files/imagelist
    defaults: { _controller: CMS2BaseBundle:File:imageList }
    methods:  [GET]
